# Generated by Django 4.2.2 on 2023-07-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunications', '0002_rename_name_comunication_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunication',
            old_name='username',
            new_name='message_name',
        ),
    ]
