# Generated by Django 4.2.2 on 2023-07-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_course_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
